// <auto-generated />
namespace DeviceBooker.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DeviceDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeviceDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201704182136201_DeviceDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
