// <auto-generated />
namespace testi7.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBRI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBRI));
        
        string IMigrationMetadata.Id
        {
            get { return "201704261058354_AddBRI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
